### ISSUE TITLE
Index Out of Range

### ISSUE THREAD

**Issue by pawann-2000** [surreal30/wordle#1]
It seems there is a List index out of Range exception, check the condition at line 16,
My python version: 3.10.5

Please refer the below imag for more:

![image](https://user-images.githubusercontent.com/59572141/175775637-92f6818f-f2ff-4148-895a-36d05fd0cc64.png)

**Comment by surreal30** [comment]
This happened because the code assumes that the letter would be 5 character long. Right now it is such. Will make it explicitly clear to enter 5 letter word so this doesn't happen. Maybe I will feature to enter any length word to it. :D

**Comment by pawann-2000** [comment]
However there is still some refactoring that needs to be done to the code, let me know once you have given the access to change the code.

thanks
